# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wouter Landuydt
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Wouter Landuydt. A Digital Design & Development student at Howest.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://wouterlanduydt.be
enforce_ssl: wouterlanduydt.be

socials:
  instagram: wouterlanduydt
  twitter: landuydtwouter
  email: wouter.landuydt@gmail.com
  linkedin: wouter-landuydt-551491120
  github: wouterlanduydt
  vimeo: wouterlanduydt

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

sass:
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
