[[redirects]]
  from = "https://wouterlanduydt.netlify.com/*"
  to = "https://wouterlanduydt.be/:splat"

[[redirects]]
  from = "https://www.wouterlanduydt.be/*"
  to = "https://wouterlanduydt.be/:splat"
